name: CodecovReport

on:
  push:
    branches: [main, ps-dev]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install
        run: npm install --force
      - name: Generate coverage report
        run: npm run ci-coverage
        continue-on-error: true
      - uses: codecov/codecov-action@v4
        with:
          flags: unittest
          fail_ci_if_error: false
          verbose: true
